pub fn print_intro() {
    println!("Piano en temps réel avec synthétiseurs avancés !");
    println!("Touches musicales :");
    println!("Notes naturelles");
    println!("Q - A");
    println!("B - B");
    println!("E - E");
    println!("C - C");
    println!("D - D");
    println!("F - F");
    println!("G - G");
    println!();
    println!("Notes dièses");
    println!("1 - C#");
    println!("2 - D#");
    println!("3 - F#");
    println!("4 - G#");
    println!("5 - A#");
    println!();
    println!("Synthétiseurs :");
    println!("W - Modular Sine        X - Modular Square");
    println!("S - Modular Sawtooth    H - Modular Hammond");
    println!("K - Modular FM");
    println!();
    println!("Contrôles :");
    println!("FLÈCHE DROITE - Octave supérieure");
    println!("FLÈCHE GAUCHE - Octave inférieure");
    println!("ESPACE - Arrêter toutes les notes");
    println!("ESC - Quitter");
}
